# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-07 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ethefux_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DeployConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethefux_app.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='parties',
            field=models.ManyToManyField(to='ethefux_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='deployconfirmation',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethefux_app.Contract'),
        ),
        migrations.AddField(
            model_name='contractproposal',
            name='partyconfirmations',
            field=models.ManyToManyField(to='ethefux_app.DeployConfirmation'),
        ),
    ]
